name: background_location_tracker_example
description: Demonstrates how to use the background_location_tracker plugin.
publish_to: 'none'

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  background_location_tracker:
    path: ../
  cupertino_icons: ^1.0.0
  permission_handler: ^5.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
